services:
  - type: web
    name: lightapp
    env: python
    plan: free
    buildCommand: git submodule update --init --recursive && pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT LightApp.app_light:app
